using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Servicefy.Package.Conventions.Generators.Emit;
using Servicefy.Package.Conventions.Models;
using Servicefy.Package.Decorators;

namespace Servicefy.Package.Conventions.ByTypeName.Generators.Emit;

/// <summary>
/// Implements <c>ServicefyConventionsBuilder.ApplyByTypeName</c> for every distinct
/// <c>.ByTypeName(predicate, lifetime)</c> call site found in the compilation: matches
/// candidates whose (namespace, type name) satisfy the predicate, then registers each
/// directly implemented interface of every matching class with the requested lifetime.
/// </summary>
internal static class ByTypeNameRegistrationEmitter
{
    internal static void Emit(
        SourceProductionContext spc,
        (Compilation Compilation, ImmutableArray<TypeNameConventionRule> Rules) source)
    {
        var (compilation, rules) = source;

        var distinctRules = rules
            .DistinctBy(r => (r.PredicateExpression, r.Lifetime))
            .ToList();

        if (distinctRules.Count == 0) return;

        var projectReferenceAssemblies = TypeCollector.GetProjectReferenceAssemblies(compilation)
            .ToHashSet<IAssemblySymbol>(SymbolEqualityComparer.Default);

        var allTypes = TypeCollector.GetAllAccessibleTypes(compilation)
            .Concat(TypeCollector.GetExternalAccessibleTypes(compilation))
            .Select(t => t.Type)
            .ToList();

        var decoratorTypes = ConventionFilters.CollectDecoratorTypes(allTypes, compilation);

        var candidates = allTypes
            .Where(t => IsRegistrable(t, decoratorTypes, projectReferenceAssemblies))
            .ToList();

        // First pass: compute matched types per rule and union all matched interfaces so
        // decorator validation runs once across the whole compilation (avoids duplicate
        // SVCFY007 diagnostics when multiple rules match overlapping interfaces).
        var ruleMatches = new List<(TypeNameConventionRule Rule, List<INamedTypeSymbol> MatchedTypes)>();
        var registeredServices = new HashSet<string>(StringComparer.Ordinal);

        foreach (var rule in distinctRules)
        {
            var matchedTypes = candidates
                .Where(t => EvaluatePredicate(rule.Predicate, t.ContainingNamespace.ToDisplayString(), t.Name))
                .OrderBy(t => t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal)
                .ToList();

            if (matchedTypes.Count == 0) continue;

            ruleMatches.Add((rule, matchedTypes));

            foreach (var type in matchedTypes)
            foreach (var iface in ConventionFilters.GetRegistrableInterfaces(type, projectReferenceAssemblies))
                registeredServices.Add(iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        }

        if (ruleMatches.Count == 0) return;

        var decoratorEntries = DecoratorCollector.CollectDecoratorEntries(compilation);
        var validDecoratorMap = DecoratorEmitter.ValidateAndBuildDecoratorMap(spc, decoratorEntries, registeredServices);

        var ns = compilation.AssemblyName ?? "Servicefy";
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine("    internal sealed partial class ServicefyConventionsBuilder");
        sb.AppendLine("    {");
        sb.AppendLine("        partial void ApplyByTypeName(Lifetime lifetime, string predicateExpression)");
        sb.AppendLine("        {");

        foreach (var (rule, matchedTypes) in ruleMatches)
        {
            sb.AppendLine($"            if (lifetime == Lifetime.{rule.Lifetime} && predicateExpression == \"{ConventionFilters.EscapeStringLiteral(rule.PredicateExpression)}\")");
            sb.AppendLine("            {");

            foreach (var type in matchedTypes)
            {
                var implFqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                foreach (var iface in ConventionFilters.GetRegistrableInterfaces(type, projectReferenceAssemblies))
                {
                    var serviceFqn = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    if (validDecoratorMap.TryGetValue(serviceFqn, out var decoratorEntry))
                        DecoratorEmitter.EmitDecoratedService(sb, "                ", "Services", rule.Lifetime, serviceFqn, implFqn, decoratorEntry);
                    else
                        sb.AppendLine($"                Services.Add{rule.Lifetime}<{serviceFqn}, {implFqn}>();");
                }
            }

            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("ServicefyConventionsBuilder.ByTypeName.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static bool IsRegistrable(INamedTypeSymbol type, HashSet<INamedTypeSymbol> decoratorTypes, HashSet<IAssemblySymbol> projectReferenceAssemblies) =>
        type.TypeKind == TypeKind.Class
        && !type.IsAbstract
        && !type.IsStatic
        && type.TypeParameters.Length == 0
        && ConventionFilters.GetRegistrableInterfaces(type, projectReferenceAssemblies).Any()
        && !ConventionFilters.InfrastructureTypeNames.Contains(type.Name)
        && !ConventionFilters.HasByConfigurationAttribute(type)
        && !decoratorTypes.Contains(type);

    private static bool EvaluatePredicate(Func<string, string, bool> predicate, string @namespace, string typeName)
    {
        try
        {
            return predicate(@namespace, typeName);
        }
        catch
        {
            return false;
        }
    }
}
