using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Servicefy.Package.Conventions.Generators.Emit;
using Servicefy.Package.Conventions.Models;
using Servicefy.Package.Decorators;
using Servicefy.Package.Diagnostics;

namespace Servicefy.Package.Conventions.ByBaseType.Generators.Emit;

/// <summary>
/// Implements <c>ServicefyConventionsBuilder.ApplyByBaseType</c> for every distinct
/// <c>.ByBaseType&lt;TBase&gt;(lifetime, selector, attribute)</c> call site found in the
/// compilation: matches types assignable to <c>TBase</c> (optionally filtered by attribute),
/// then registers them according to the requested <c>ServiceTypeSelector</c>.
/// </summary>
internal static class ByBaseTypeRegistrationEmitter
{
    internal static void Emit(
        SourceProductionContext spc,
        (Compilation Compilation, ImmutableArray<ByBaseTypeConventionRule> Rules) source)
    {
        var (compilation, rules) = source;

        var distinctRules = rules
            .DistinctBy(r => (r.BaseTypeFqn, r.Lifetime, r.Selector, r.AttributeFqn))
            .ToList();

        if (distinctRules.Count == 0) return;

        // SVCFY010: Self ignores TBase entirely and registers the matched concrete types as
        // themselves, so an interface TBase (which carries no usable "self" type) is rejected.
        distinctRules = distinctRules
            .Where(r =>
            {
                if (r.Selector != "Self" || r.BaseType.TypeKind != TypeKind.Interface) return true;

                spc.ReportDiagnostic(new SVCFY010(r.BaseTypeLocation).CreateDiagnostic(r.BaseTypeFqn));
                return false;
            })
            .ToList();

        if (distinctRules.Count == 0) return;

        var projectReferenceAssemblies = TypeCollector.GetProjectReferenceAssemblies(compilation)
            .ToHashSet<IAssemblySymbol>(SymbolEqualityComparer.Default);

        var allTypes = TypeCollector.GetAllAccessibleTypes(compilation)
            .Concat(TypeCollector.GetExternalAccessibleTypes(compilation))
            .Select(t => t.Type)
            .ToList();

        var decoratorTypes = ConventionFilters.CollectDecoratorTypes(allTypes, compilation);

        var registrableTypes = allTypes
            .Where(t => IsRegistrable(t, decoratorTypes))
            .ToList();

        // First pass: compute matched types per rule and union all target service FQNs so
        // decorator validation runs once across the whole compilation (avoids duplicate
        // SVCFY007 diagnostics when multiple rules target overlapping interfaces).
        var ruleMatches = new List<(ByBaseTypeConventionRule Rule, List<INamedTypeSymbol> MatchedTypes)>();
        var registeredServices = new HashSet<string>(StringComparer.Ordinal);

        foreach (var rule in distinctRules)
        {
            var matchedTypes = registrableTypes
                .Where(t => IsAssignableTo(t, rule.BaseType))
                .Where(t => rule.AttributeType is null || HasAttribute(t, rule.AttributeType))
                .OrderBy(t => t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal)
                .ToList();

            if (matchedTypes.Count == 0) continue;

            ruleMatches.Add((rule, matchedTypes));

            foreach (var serviceFqn in GetTargetServiceFqns(matchedTypes, rule, projectReferenceAssemblies))
                registeredServices.Add(serviceFqn);
        }

        if (ruleMatches.Count == 0) return;

        var decoratorEntries = DecoratorCollector.CollectDecoratorEntries(compilation);
        var validDecoratorMap = DecoratorEmitter.ValidateAndBuildDecoratorMap(spc, decoratorEntries, registeredServices);

        var ns = compilation.AssemblyName ?? "Servicefy";
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine("    internal sealed partial class ServicefyConventionsBuilder");
        sb.AppendLine("    {");
        sb.AppendLine("        partial void ApplyByBaseType(Type baseType, Lifetime lifetime, ServiceTypeSelector selector, Type matchAttribute)");
        sb.AppendLine("        {");

        foreach (var (rule, matchedTypes) in ruleMatches)
        {
            var attributeExpr = rule.AttributeFqn is null ? "null" : $"typeof({rule.AttributeFqn})";
            sb.AppendLine($"            if (baseType == typeof({rule.BaseTypeFqn}) && lifetime == Lifetime.{rule.Lifetime} && selector == ServiceTypeSelector.{rule.Selector} && matchAttribute == {attributeExpr})");
            sb.AppendLine("            {");

            EmitRegistrations(sb, "                ", rule, matchedTypes, validDecoratorMap, projectReferenceAssemblies);

            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("ServicefyConventionsBuilder.ByBaseType.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static void EmitRegistrations(
        StringBuilder sb,
        string indent,
        ByBaseTypeConventionRule rule,
        List<INamedTypeSymbol> matchedTypes,
        Dictionary<string, InterfaceDecoratorEntry> validDecoratorMap,
        HashSet<IAssemblySymbol> projectReferenceAssemblies)
    {
        switch (rule.Selector)
        {
            case "BaseType":
                EmitAgainstService(sb, indent, rule.Lifetime, rule.BaseTypeFqn, matchedTypes, validDecoratorMap);
                break;

            case "ImplementedInterfaces":
                var ifaceCounts = matchedTypes
                    .SelectMany(t => ConventionFilters.GetRegistrableInterfaces(t, projectReferenceAssemblies))
                    .GroupBy(i => i.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal)
                    .ToDictionary(g => g.Key, g => g.Count(), StringComparer.Ordinal);

                foreach (var type in matchedTypes)
                {
                    var implFqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    foreach (var iface in ConventionFilters.GetRegistrableInterfaces(type, projectReferenceAssemblies))
                    {
                        var serviceFqn = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        if (ifaceCounts[serviceFqn] == 1 && validDecoratorMap.TryGetValue(serviceFqn, out var entry))
                            DecoratorEmitter.EmitDecoratedService(sb, indent, "Services", rule.Lifetime, serviceFqn, implFqn, entry);
                        else
                            sb.AppendLine($"{indent}Services.Add{rule.Lifetime}<{serviceFqn}, {implFqn}>();");
                    }
                }

                break;

            case "Self":
                foreach (var type in matchedTypes)
                {
                    var implFqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    sb.AppendLine($"{indent}Services.Add{rule.Lifetime}<{implFqn}>();");
                }

                break;

            case "SelfWithInterfaces":
                foreach (var type in matchedTypes)
                {
                    var implFqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    sb.AppendLine($"{indent}Services.Add{rule.Lifetime}<{implFqn}>();");

                    foreach (var iface in ConventionFilters.GetRegistrableInterfaces(type, projectReferenceAssemblies))
                    {
                        var serviceFqn = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                        sb.AppendLine($"{indent}Services.Add{rule.Lifetime}<{serviceFqn}>(sp => sp.GetRequiredService<{implFqn}>());");
                    }
                }

                break;
        }
    }

    private static void EmitAgainstService(
        StringBuilder sb,
        string indent,
        string lifetime,
        string serviceFqn,
        List<INamedTypeSymbol> matchedTypes,
        Dictionary<string, InterfaceDecoratorEntry> validDecoratorMap)
    {
        if (matchedTypes.Count == 1 && validDecoratorMap.TryGetValue(serviceFqn, out var entry))
        {
            var implFqn = matchedTypes[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            DecoratorEmitter.EmitDecoratedService(sb, indent, "Services", lifetime, serviceFqn, implFqn, entry);
            return;
        }

        foreach (var type in matchedTypes)
        {
            var implFqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"{indent}Services.Add{lifetime}<{serviceFqn}, {implFqn}>();");
        }
    }

    private static IEnumerable<string> GetTargetServiceFqns(
        List<INamedTypeSymbol> matchedTypes, ByBaseTypeConventionRule rule, HashSet<IAssemblySymbol> projectReferenceAssemblies)
    {
        switch (rule.Selector)
        {
            case "BaseType":
                yield return rule.BaseTypeFqn;
                break;

            case "ImplementedInterfaces":
                foreach (var type in matchedTypes)
                foreach (var iface in ConventionFilters.GetRegistrableInterfaces(type, projectReferenceAssemblies))
                    yield return iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

                break;
        }
    }

    private static bool IsRegistrable(INamedTypeSymbol type, HashSet<INamedTypeSymbol> decoratorTypes) =>
        type.TypeKind == TypeKind.Class
        && !type.IsAbstract
        && !type.IsStatic
        && type.TypeParameters.Length == 0
        && !ConventionFilters.InfrastructureTypeNames.Contains(type.Name)
        && !ConventionFilters.HasByConfigurationAttribute(type)
        && !decoratorTypes.Contains(type);

    private static bool IsAssignableTo(INamedTypeSymbol type, INamedTypeSymbol baseType)
    {
        if (baseType.TypeKind == TypeKind.Interface)
            return type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, baseType));

        return WalkBaseTypes(type).Any(t => SymbolEqualityComparer.Default.Equals(t, baseType));
    }

    private static IEnumerable<INamedTypeSymbol> WalkBaseTypes(INamedTypeSymbol type)
    {
        INamedTypeSymbol? current = type;
        while (current is not null)
        {
            yield return current;
            current = current.BaseType;
        }
    }

    private static bool HasAttribute(INamedTypeSymbol type, INamedTypeSymbol attributeType) =>
        type.GetAttributes().Any(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, attributeType));
}
