using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using Servicefy.Package.Conventions.Generators.Emit;
using Servicefy.Package.Conventions.Models;
using Servicefy.Package.Decorators;

namespace Servicefy.Package.Conventions.ByNamespaceOf.Generators.Emit;

/// <summary>
/// Implements <c>ServicefyConventionsBuilder.ApplyByNamespaceOf</c> for every distinct
/// <c>.ByNamespaceOf&lt;TMarker&gt;(predicate, lifetime)</c> call site found in the compilation:
/// restricts candidates to <typeparamref name="TMarker"/>'s namespace (or a sub-namespace of it),
/// matches the remaining namespaces against the predicate, then registers each directly
/// implemented interface of every matching class with the requested lifetime.
/// </summary>
internal static class ByNamespaceOfRegistrationEmitter
{
    internal static void Emit(
        SourceProductionContext spc,
        (Compilation Compilation, ImmutableArray<NamespaceOfConventionRule> Rules) source)
    {
        var (compilation, rules) = source;

        var distinctRules = rules
            .DistinctBy(r => (r.MarkerTypeFqn, r.PredicateExpression, r.Lifetime))
            .ToList();

        if (distinctRules.Count == 0) return;

        var projectReferenceAssemblies = TypeCollector.GetProjectReferenceAssemblies(compilation)
            .ToHashSet<IAssemblySymbol>(SymbolEqualityComparer.Default);

        var allTypes = TypeCollector.GetAllAccessibleTypes(compilation)
            .Concat(TypeCollector.GetExternalAccessibleTypes(compilation))
            .Select(t => t.Type)
            .ToList();

        var decoratorTypes = ConventionFilters.CollectDecoratorTypes(allTypes, compilation);

        var namespaceGroups = allTypes
            .Where(t => IsRegistrable(t, decoratorTypes, projectReferenceAssemblies))
            .GroupBy(t => t.ContainingNamespace.ToDisplayString(), StringComparer.Ordinal)
            .ToList();

        // First pass: compute matched types per rule and union all matched interfaces so
        // decorator validation runs once across the whole compilation (avoids duplicate
        // SVCFY007 diagnostics when multiple rules match overlapping interfaces).
        var ruleMatches = new List<(NamespaceOfConventionRule Rule, List<INamedTypeSymbol> MatchedTypes)>();
        var registeredServices = new HashSet<string>(StringComparer.Ordinal);

        foreach (var rule in distinctRules)
        {
            var matchedTypes = namespaceGroups
                .Where(g => IsWithinRoot(g.Key, rule.RootNamespace) && EvaluatePredicate(rule.Predicate, g.Key))
                .SelectMany(g => g)
                .OrderBy(t => t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal)
                .ToList();

            if (matchedTypes.Count == 0) continue;

            ruleMatches.Add((rule, matchedTypes));

            foreach (var type in matchedTypes)
            foreach (var iface in ConventionFilters.GetRegistrableInterfaces(type, projectReferenceAssemblies))
                registeredServices.Add(iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        }

        if (ruleMatches.Count == 0) return;

        var decoratorEntries = DecoratorCollector.CollectDecoratorEntries(compilation);
        var validDecoratorMap = DecoratorEmitter.ValidateAndBuildDecoratorMap(spc, decoratorEntries, registeredServices);

        var ns = compilation.AssemblyName ?? "Servicefy";
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {ns}");
        sb.AppendLine("{");
        sb.AppendLine("    internal sealed partial class ServicefyConventionsBuilder");
        sb.AppendLine("    {");
        sb.AppendLine("        partial void ApplyByNamespaceOf(Type markerType, Lifetime lifetime, string predicateExpression)");
        sb.AppendLine("        {");

        foreach (var (rule, matchedTypes) in ruleMatches)
        {
            sb.AppendLine($"            if (markerType == typeof({rule.MarkerTypeFqn}) && lifetime == Lifetime.{rule.Lifetime} && predicateExpression == \"{ConventionFilters.EscapeStringLiteral(rule.PredicateExpression)}\")");
            sb.AppendLine("            {");

            foreach (var type in matchedTypes)
            {
                var implFqn = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                foreach (var iface in ConventionFilters.GetRegistrableInterfaces(type, projectReferenceAssemblies))
                {
                    var serviceFqn = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    if (validDecoratorMap.TryGetValue(serviceFqn, out var decoratorEntry))
                        DecoratorEmitter.EmitDecoratedService(sb, "                ", "Services", rule.Lifetime, serviceFqn, implFqn, decoratorEntry);
                    else
                        sb.AppendLine($"                Services.Add{rule.Lifetime}<{serviceFqn}, {implFqn}>();");
                }
            }

            sb.AppendLine("                return;");
            sb.AppendLine("            }");
            sb.AppendLine();
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("ServicefyConventionsBuilder.ByNamespaceOf.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    // A namespace is "within" the marker's root namespace if it is the root namespace itself,
    // or a sub-namespace of it. A root of "" (TMarker in the global namespace) imposes no
    // restriction, since the global namespace has no meaningful sub-namespace prefix to match.
    private static bool IsWithinRoot(string @namespace, string root) =>
        root.Length == 0
        || @namespace == root
        || @namespace.StartsWith(root + ".", StringComparison.Ordinal);

    private static bool IsRegistrable(INamedTypeSymbol type, HashSet<INamedTypeSymbol> decoratorTypes, HashSet<IAssemblySymbol> projectReferenceAssemblies) =>
        type.TypeKind == TypeKind.Class
        && !type.IsAbstract
        && !type.IsStatic
        && type.TypeParameters.Length == 0
        && ConventionFilters.GetRegistrableInterfaces(type, projectReferenceAssemblies).Any()
        && !ConventionFilters.InfrastructureTypeNames.Contains(type.Name)
        && !ConventionFilters.HasByConfigurationAttribute(type)
        && !decoratorTypes.Contains(type);

    private static bool EvaluatePredicate(Func<string, bool> predicate, string @namespace)
    {
        try
        {
            return predicate(@namespace);
        }
        catch
        {
            return false;
        }
    }
}
